graph LR
start -->|dot<br>-31.9| dot0['.'<br>-31.9]
start -->|dash<br>-0.1| dash0['-'<br>-0.1]
dot0 -->|symbol gap<br> -0.0| symbol1['.'<br>-32.0]
dot0 -->|letter gap<br>-12.2| letter1['E'<br>-44.1]
dot0 -->|word gap<br>-520.8| word1['E '<br>-552.7]
dash0 -->|symbol gap<br> -0.0| symbol2['-'<br>-0.2]
dash0 -->|letter gap<br>-12.2| letter2['T'<br>-12.3]
dash0 -->|word gap<br>-520.8| word2['T '<br>-520.9]
word1 -->|dot<br>-0.1| dot3['E .'<br>-552.8]
word1 -->|dash<br>-44.0| dash3['E -'<br>-596.7]
word2 -->|dot<br>-0.1| dot4['T .'<br>-521.0]
word2 -->|dash<br>-44.0| dash4['T -'<br>-564.9]
letter1 -->|dot<br>-0.1| dot5['E.'<br>-44.2]
letter1 -->|dash<br>-44.0| dash5['E-'<br>-88.1]
symbol1 -->|dot<br>-0.1| dot6['.'<br>-32.1]
symbol1 -->|dash<br>-44.0| dash6['-'<br>-76.0]
letter2 -->|dot<br>-0.1| dot7['T.'<br>-12.4]
letter2 -->|dash<br>-44.0| dash7['T-'<br>-56.3]
symbol2 -->|dot<br>-0.1| dot8['.'<br>-0.3]
symbol2 -->|dash<br>-44.0| dash8['-'<br>-44.2]
dot3 -->|symbol gap<br> -0.1| symbol9['E .'<br>-552.9]
dot3 -->|letter gap<br>-10.2| letter9['E E'<br>-563.0]
dot3 -->|word gap<br>-494.1| word9['E E '<br>-1046.9]
dash3 -->|symbol gap<br> -0.1| symbol10['E -'<br>-596.8]
dash3 -->|letter gap<br>-10.2| letter10['E T'<br>-606.9]
dash3 -->|word gap<br>-494.1| word10['E T '<br>-1090.8]
dot4 -->|symbol gap<br> -0.1| symbol11['T .'<br>-521.1]
dot4 -->|letter gap<br>-10.2| letter11['T E'<br>-531.2]
dot4 -->|word gap<br>-494.1| word11['T E '<br>-1015.1]
dash4 -->|symbol gap<br> -0.1| symbol12['T -'<br>-565.0]
dash4 -->|letter gap<br>-10.2| letter12['T T'<br>-575.1]
dash4 -->|word gap<br>-494.1| word12['T T '<br>-1059.0]
dot5 -->|symbol gap<br> -0.1| symbol13['E.'<br>-44.4]
dot5 -->|letter gap<br>-10.2| letter13['EE'<br>-54.4]
dot5 -->|word gap<br>-494.1| word13['EE '<br>-538.3]
dash5 -->|symbol gap<br> -0.1| symbol14['E-'<br>-88.2]
dash5 -->|letter gap<br>-10.2| letter14['ET'<br>-98.3]
dash5 -->|word gap<br>-494.1| word14['ET '<br>-582.2]
dot6 -->|symbol gap<br> -0.1| symbol15['..'<br>-32.2]
dot6 -->|letter gap<br>-10.2| letter15['I'<br>-42.3]
dot6 -->|word gap<br>-494.1| word15['I '<br>-526.2]
dash6 -->|symbol gap<br> -0.1| symbol16['.-'<br>-76.1]
dash6 -->|letter gap<br>-10.2| letter16['A'<br>-86.2]
dash6 -->|word gap<br>-494.1| word16['A '<br>-570.0]
dot7 -->|symbol gap<br> -0.1| symbol17['T.'<br>-12.6]
dot7 -->|letter gap<br>-10.2| letter17['TE'<br>-22.6]
dot7 -->|word gap<br>-494.1| word17['TE '<br>-506.5]
dash7 -->|symbol gap<br> -0.1| symbol18['T-'<br>-56.4]
dash7 -->|letter gap<br>-10.2| letter18['TT'<br>-66.5]
dash7 -->|word gap<br>-494.1| word18['TT '<br>-550.4]
dot8 -->|symbol gap<br> -0.1| symbol19['-.'<br>-0.4]
dot8 -->|letter gap<br>-10.2| letter19['N'<br>-10.5]
dot8 -->|word gap<br>-494.1| word19['N '<br>-494.4]
dash8 -->|symbol gap<br> -0.1| symbol20['--'<br>-44.3]
dash8 -->|letter gap<br>-10.2| letter20['M'<br>-54.4]
dash8 -->|word gap<br>-494.1| word20['M '<br>-538.2]
word10 -->|dot<br>-0.7| dot21['E T .'<br>-1091.4]
word10 -->|dash<br>-52.0| dash21['E T -'<br>-1142.8]
word12 -->|dot<br>-0.7| dot22['T T .'<br>-1059.6]
word12 -->|dash<br>-52.0| dash22['T T -'<br>-1111.0]
word9 -->|dot<br>-0.7| dot23['E E .'<br>-1047.5]
word9 -->|dash<br>-52.0| dash23['E E -'<br>-1098.9]
word11 -->|dot<br>-0.7| dot24['T E .'<br>-1015.7]
word11 -->|dash<br>-52.0| dash24['T E -'<br>-1067.1]
letter10 -->|dot<br>-0.7| dot25['E T.'<br>-607.5]
letter10 -->|dash<br>-52.0| dash25['E T-'<br>-658.9]
symbol10 -->|dot<br>-0.7| dot26['E .'<br>-597.5]
symbol10 -->|dash<br>-52.0| dash26['E -'<br>-648.8]
word14 -->|dot<br>-0.7| dot27['ET .'<br>-582.9]
word14 -->|dash<br>-52.0| dash27['ET -'<br>-634.2]
letter12 -->|dot<br>-0.7| dot28['T T.'<br>-575.7]
letter12 -->|dash<br>-52.0| dash28['T T-'<br>-627.1]
word16 -->|dot<br>-0.7| dot29['A .'<br>-570.7]
word16 -->|dash<br>-52.0| dash29['A -'<br>-622.1]
symbol12 -->|dot<br>-0.7| dot30['T .'<br>-565.7]
symbol12 -->|dash<br>-52.0| dash30['T -'<br>-617.0]
letter9 -->|dot<br>-0.7| dot31['E E.'<br>-563.7]
letter9 -->|dash<br>-52.0| dash31['E E-'<br>-615.0]
symbol9 -->|dot<br>-0.7| dot32['E .'<br>-553.6]
symbol9 -->|dash<br>-52.0| dash32['E -'<br>-605.0]
word18 -->|dot<br>-0.7| dot33['TT .'<br>-551.1]
word18 -->|dash<br>-52.0| dash33['TT -'<br>-602.4]
word13 -->|dot<br>-0.7| dot34['EE .'<br>-539.0]
word13 -->|dash<br>-52.0| dash34['EE -'<br>-590.3]
word20 -->|dot<br>-0.7| dot35['M .'<br>-538.9]
word20 -->|dash<br>-52.0| dash35['M -'<br>-590.3]
letter11 -->|dot<br>-0.7| dot36['T E.'<br>-531.9]
letter11 -->|dash<br>-52.0| dash36['T E-'<br>-583.2]
word15 -->|dot<br>-0.7| dot37['I .'<br>-526.8]
word15 -->|dash<br>-52.0| dash37['I -'<br>-578.2]
symbol11 -->|dot<br>-0.7| dot38['T .'<br>-521.8]
symbol11 -->|dash<br>-52.0| dash38['T -'<br>-573.2]
word17 -->|dot<br>-0.7| dot39['TE .'<br>-507.2]
word17 -->|dash<br>-52.0| dash39['TE -'<br>-558.5]
word19 -->|dot<br>-0.7| dot40['N .'<br>-495.0]
word19 -->|dash<br>-52.0| dash40['N -'<br>-546.4]
letter14 -->|dot<br>-0.7| dot41['ET.'<br>-99.0]
letter14 -->|dash<br>-52.0| dash41['ET-'<br>-150.3]
symbol14 -->|dot<br>-0.7| dot42['E.'<br>-88.9]
symbol14 -->|dash<br>-52.0| dash42['E-'<br>-140.3]
letter16 -->|dot<br>-0.7| dot43['A.'<br>-86.8]
letter16 -->|dash<br>-52.0| dash43['A-'<br>-138.2]
symbol16 -->|dot<br>-0.7| dot44['.'<br>-76.8]
symbol16 -->|dash<br>-52.0| dash44['-'<br>-128.1]
letter18 -->|dot<br>-0.7| dot45['TT.'<br>-67.2]
letter18 -->|dash<br>-52.0| dash45['TT-'<br>-118.5]
symbol18 -->|dot<br>-0.7| dot46['T.'<br>-57.1]
symbol18 -->|dash<br>-52.0| dash46['T-'<br>-108.5]
letter13 -->|dot<br>-0.7| dot47['EE.'<br>-55.1]
letter13 -->|dash<br>-52.0| dash47['EE-'<br>-106.5]
letter20 -->|dot<br>-0.7| dot48['M.'<br>-55.0]
letter20 -->|dash<br>-52.0| dash48['M-'<br>-106.4]
symbol13 -->|dot<br>-0.7| dot49['E.'<br>-45.0]
symbol13 -->|dash<br>-52.0| dash49['E-'<br>-96.4]
symbol20 -->|dot<br>-0.7| dot50['.'<br>-45.0]
symbol20 -->|dash<br>-52.0| dash50['-'<br>-96.3]
letter15 -->|dot<br>-0.7| dot51['I.'<br>-42.9]
letter15 -->|dash<br>-52.0| dash51['I-'<br>-94.3]
symbol15 -->|dot<br>-0.7| dot52['.'<br>-32.9]
symbol15 -->|dash<br>-52.0| dash52['-'<br>-84.2]
letter17 -->|dot<br>-0.7| dot53['TE.'<br>-23.3]
letter17 -->|dash<br>-52.0| dash53['TE-'<br>-74.7]
symbol17 -->|dot<br>-0.7| dot54['T.'<br>-13.2]
symbol17 -->|dash<br>-52.0| dash54['T-'<br>-64.6]
letter19 -->|dot<br>-0.7| dot55['N.'<br>-11.1]
letter19 -->|dash<br>-52.0| dash55['N-'<br>-62.5]
symbol19 -->|dot<br>-0.7| dot56['.'<br>-1.1]
symbol19 -->|dash<br>-52.0| dash56['-'<br>-52.4]
dot21 -->|symbol gap<br> -20.4| symbol57['E T .'<br>-1111.9]
dot21 -->|letter gap<br>-1.3| letter57['E T E'<br>-1092.7]
dot21 -->|word gap<br>-327.0| word57['E T E '<br>-1418.5]
dash21 -->|symbol gap<br> -20.4| symbol58['E T -'<br>-1163.2]
dash21 -->|letter gap<br>-1.3| letter58['E T T'<br>-1144.1]
dash21 -->|word gap<br>-327.0| word58['E T T '<br>-1469.8]
dot22 -->|symbol gap<br> -20.4| symbol59['T T .'<br>-1080.1]
dot22 -->|letter gap<br>-1.3| letter59['T T E'<br>-1060.9]
dot22 -->|word gap<br>-327.0| word59['T T E '<br>-1386.7]
dash22 -->|symbol gap<br> -20.4| symbol60['T T -'<br>-1131.4]
dash22 -->|letter gap<br>-1.3| letter60['T T T'<br>-1112.3]
dash22 -->|word gap<br>-327.0| word60['T T T '<br>-1438.0]
dot23 -->|symbol gap<br> -20.4| symbol61['E E .'<br>-1068.0]
dot23 -->|letter gap<br>-1.3| letter61['E E E'<br>-1048.8]
dot23 -->|word gap<br>-327.0| word61['E E E '<br>-1374.6]
dash23 -->|symbol gap<br> -20.4| symbol62['E E -'<br>-1119.3]
dash23 -->|letter gap<br>-1.3| letter62['E E T'<br>-1100.2]
dash23 -->|word gap<br>-327.0| word62['E E T '<br>-1426.0]
dot24 -->|symbol gap<br> -20.4| symbol63['T E .'<br>-1036.2]
dot24 -->|letter gap<br>-1.3| letter63['T E E'<br>-1017.0]
dot24 -->|word gap<br>-327.0| word63['T E E '<br>-1342.8]
dash24 -->|symbol gap<br> -20.4| symbol64['T E -'<br>-1087.5]
dash24 -->|letter gap<br>-1.3| letter64['T E T'<br>-1068.4]
dash24 -->|word gap<br>-327.0| word64['T E T '<br>-1394.2]
dot25 -->|symbol gap<br> -20.4| symbol65['E T.'<br>-628.0]
dot25 -->|letter gap<br>-1.3| letter65['E TE'<br>-608.8]
dot25 -->|word gap<br>-327.0| word65['E TE '<br>-934.6]
dash25 -->|symbol gap<br> -20.4| symbol66['E T-'<br>-679.4]
dash25 -->|letter gap<br>-1.3| letter66['E TT'<br>-660.2]
dash25 -->|word gap<br>-327.0| word66['E TT '<br>-986.0]
dot26 -->|symbol gap<br> -20.4| symbol67['E -.'<br>-617.9]
dot26 -->|letter gap<br>-1.3| letter67['E N'<br>-598.7]
dot26 -->|word gap<br>-327.0| word67['E N '<br>-924.5]
dash26 -->|symbol gap<br> -20.4| symbol68['E --'<br>-669.3]
dash26 -->|letter gap<br>-1.3| letter68['E M'<br>-650.1]
dash26 -->|word gap<br>-327.0| word68['E M '<br>-975.9]
dot27 -->|symbol gap<br> -20.4| symbol69['ET .'<br>-603.3]
dot27 -->|letter gap<br>-1.3| letter69['ET E'<br>-584.1]
dot27 -->|word gap<br>-327.0| word69['ET E '<br>-909.9]
dash27 -->|symbol gap<br> -20.4| symbol70['ET -'<br>-654.7]
dash27 -->|letter gap<br>-1.3| letter70['ET T'<br>-635.5]
dash27 -->|word gap<br>-327.0| word70['ET T '<br>-961.3]
dot28 -->|symbol gap<br> -20.4| symbol71['T T.'<br>-596.2]
dot28 -->|letter gap<br>-1.3| letter71['T TE'<br>-577.0]
dot28 -->|word gap<br>-327.0| word71['T TE '<br>-902.8]
dash28 -->|symbol gap<br> -20.4| symbol72['T T-'<br>-647.6]
dash28 -->|letter gap<br>-1.3| letter72['T TT'<br>-628.4]
dash28 -->|word gap<br>-327.0| word72['T TT '<br>-954.2]
dot29 -->|symbol gap<br> -20.4| symbol73['A .'<br>-591.1]
dot29 -->|letter gap<br>-1.3| letter73['A E'<br>-572.0]
dot29 -->|word gap<br>-327.0| word73['A E '<br>-897.8]
dash29 -->|symbol gap<br> -20.4| symbol74['A -'<br>-642.5]
dash29 -->|letter gap<br>-1.3| letter74['A T'<br>-623.3]
dash29 -->|word gap<br>-327.0| word74['A T '<br>-949.1]
dot30 -->|symbol gap<br> -20.4| symbol75['T -.'<br>-586.1]
dot30 -->|letter gap<br>-1.3| letter75['T N'<br>-566.9]
dot30 -->|word gap<br>-327.0| word75['T N '<br>-892.7]
dash30 -->|symbol gap<br> -20.4| symbol76['T --'<br>-637.5]
dash30 -->|letter gap<br>-1.3| letter76['T M'<br>-618.3]
dash30 -->|word gap<br>-327.0| word76['T M '<br>-944.1]
dot31 -->|symbol gap<br> -20.4| symbol77['E E.'<br>-584.1]
dot31 -->|letter gap<br>-1.3| letter77['E EE'<br>-564.9]
dot31 -->|word gap<br>-327.0| word77['E EE '<br>-890.7]
dash31 -->|symbol gap<br> -20.4| symbol78['E E-'<br>-635.5]
dash31 -->|letter gap<br>-1.3| letter78['E ET'<br>-616.3]
dash31 -->|word gap<br>-327.0| word78['E ET '<br>-942.1]
dot32 -->|symbol gap<br> -20.4| symbol79['E ..'<br>-574.0]
dot32 -->|letter gap<br>-1.3| letter79['E I'<br>-554.8]
dot32 -->|word gap<br>-327.0| word79['E I '<br>-880.6]
dash32 -->|symbol gap<br> -20.4| symbol80['E .-'<br>-625.4]
dash32 -->|letter gap<br>-1.3| letter80['E A'<br>-606.2]
dash32 -->|word gap<br>-327.0| word80['E A '<br>-932.0]
dot33 -->|symbol gap<br> -20.4| symbol81['TT .'<br>-571.5]
dot33 -->|letter gap<br>-1.3| letter81['TT E'<br>-552.3]
dot33 -->|word gap<br>-327.0| word81['TT E '<br>-878.1]
dash33 -->|symbol gap<br> -20.4| symbol82['TT -'<br>-622.9]
dash33 -->|letter gap<br>-1.3| letter82['TT T'<br>-603.7]
dash33 -->|word gap<br>-327.0| word82['TT T '<br>-929.5]
dot34 -->|symbol gap<br> -20.4| symbol83['EE .'<br>-559.4]
dot34 -->|letter gap<br>-1.3| letter83['EE E'<br>-540.2]
dot34 -->|word gap<br>-327.0| word83['EE E '<br>-866.0]
dash34 -->|symbol gap<br> -20.4| symbol84['EE -'<br>-610.8]
dash34 -->|letter gap<br>-1.3| letter84['EE T'<br>-591.6]
dash34 -->|word gap<br>-327.0| word84['EE T '<br>-917.4]
dot35 -->|symbol gap<br> -20.4| symbol85['M .'<br>-559.3]
dot35 -->|letter gap<br>-1.3| letter85['M E'<br>-540.2]
dot35 -->|word gap<br>-327.0| word85['M E '<br>-866.0]
dash35 -->|symbol gap<br> -20.4| symbol86['M -'<br>-610.7]
dash35 -->|letter gap<br>-1.3| letter86['M T'<br>-591.5]
dash35 -->|word gap<br>-327.0| word86['M T '<br>-917.3]
dot36 -->|symbol gap<br> -20.4| symbol87['T E.'<br>-552.3]
dot36 -->|letter gap<br>-1.3| letter87['T EE'<br>-533.1]
dot36 -->|word gap<br>-327.0| word87['T EE '<br>-858.9]
dash36 -->|symbol gap<br> -20.4| symbol88['T E-'<br>-603.7]
dash36 -->|letter gap<br>-1.3| letter88['T ET'<br>-584.5]
dash36 -->|word gap<br>-327.0| word88['T ET '<br>-910.3]
dot37 -->|symbol gap<br> -20.4| symbol89['I .'<br>-547.3]
dot37 -->|letter gap<br>-1.3| letter89['I E'<br>-528.1]
dot37 -->|word gap<br>-327.0| word89['I E '<br>-853.9]
dash37 -->|symbol gap<br> -20.4| symbol90['I -'<br>-598.6]
dash37 -->|letter gap<br>-1.3| letter90['I T'<br>-579.5]
dash37 -->|word gap<br>-327.0| word90['I T '<br>-905.2]
dot38 -->|symbol gap<br> -20.4| symbol91['T ..'<br>-542.2]
dot38 -->|letter gap<br>-1.3| letter91['T I'<br>-523.0]
dot38 -->|word gap<br>-327.0| word91['T I '<br>-848.8]
dash38 -->|symbol gap<br> -20.4| symbol92['T .-'<br>-593.6]
dash38 -->|letter gap<br>-1.3| letter92['T A'<br>-574.4]
dash38 -->|word gap<br>-327.0| word92['T A '<br>-900.2]
dot39 -->|symbol gap<br> -20.4| symbol93['TE .'<br>-527.6]
dot39 -->|letter gap<br>-1.3| letter93['TE E'<br>-508.4]
dot39 -->|word gap<br>-327.0| word93['TE E '<br>-834.2]
dash39 -->|symbol gap<br> -20.4| symbol94['TE -'<br>-579.0]
dash39 -->|letter gap<br>-1.3| letter94['TE T'<br>-559.8]
dash39 -->|word gap<br>-327.0| word94['TE T '<br>-885.6]
dot40 -->|symbol gap<br> -20.4| symbol95['N .'<br>-515.5]
dot40 -->|letter gap<br>-1.3| letter95['N E'<br>-496.3]
dot40 -->|word gap<br>-327.0| word95['N E '<br>-822.1]
dash40 -->|symbol gap<br> -20.4| symbol96['N -'<br>-566.8]
dash40 -->|letter gap<br>-1.3| letter96['N T'<br>-547.7]
dash40 -->|word gap<br>-327.0| word96['N T '<br>-873.4]
dot41 -->|symbol gap<br> -20.4| symbol97['ET.'<br>-119.4]
dot41 -->|letter gap<br>-1.3| letter97['ETE'<br>-100.2]
dot41 -->|word gap<br>-327.0| word97['ETE '<br>-426.0]
dash41 -->|symbol gap<br> -20.4| symbol98['ET-'<br>-170.8]
dash41 -->|letter gap<br>-1.3| letter98['ETT'<br>-151.6]
dash41 -->|word gap<br>-327.0| word98['ETT '<br>-477.4]
dot42 -->|symbol gap<br> -20.4| symbol99['E-.'<br>-109.3]
dot42 -->|letter gap<br>-1.3| letter99['EN'<br>-90.2]
dot42 -->|word gap<br>-327.0| word99['EN '<br>-415.9]
dash42 -->|symbol gap<br> -20.4| symbol100['E--'<br>-160.7]
dash42 -->|letter gap<br>-1.3| letter100['EM'<br>-141.5]
dash42 -->|word gap<br>-327.0| word100['EM '<br>-467.3]
dot43 -->|symbol gap<br> -20.4| symbol101['A.'<br>-107.3]
dot43 -->|letter gap<br>-1.3| letter101['AE'<br>-88.1]
dot43 -->|word gap<br>-327.0| word101['AE '<br>-413.9]
dash43 -->|symbol gap<br> -20.4| symbol102['A-'<br>-158.6]
dash43 -->|letter gap<br>-1.3| letter102['AT'<br>-139.5]
dash43 -->|word gap<br>-327.0| word102['AT '<br>-465.2]
dot44 -->|symbol gap<br> -20.4| symbol103['.-.'<br>-97.2]
dot44 -->|letter gap<br>-1.3| letter103['R'<br>-78.0]
dot44 -->|word gap<br>-327.0| word103['R '<br>-403.8]
dash44 -->|symbol gap<br> -20.4| symbol104['.--'<br>-148.6]
dash44 -->|letter gap<br>-1.3| letter104['W'<br>-129.4]
dash44 -->|word gap<br>-327.0| word104['W '<br>-455.2]
dot45 -->|symbol gap<br> -20.4| symbol105['TT.'<br>-87.6]
dot45 -->|letter gap<br>-1.3| letter105['TTE'<br>-68.4]
dot45 -->|word gap<br>-327.0| word105['TTE '<br>-394.2]
dash45 -->|symbol gap<br> -20.4| symbol106['TT-'<br>-139.0]
dash45 -->|letter gap<br>-1.3| letter106['TTT'<br>-119.8]
dash45 -->|word gap<br>-327.0| word106['TTT '<br>-445.6]
dot46 -->|symbol gap<br> -20.4| symbol107['T-.'<br>-77.5]
dot46 -->|letter gap<br>-1.3| letter107['TN'<br>-58.4]
dot46 -->|word gap<br>-327.0| word107['TN '<br>-384.1]
dash46 -->|symbol gap<br> -20.4| symbol108['T--'<br>-128.9]
dash46 -->|letter gap<br>-1.3| letter108['TM'<br>-109.7]
dash46 -->|word gap<br>-327.0| word108['TM '<br>-435.5]
dot47 -->|symbol gap<br> -20.4| symbol109['EE.'<br>-75.5]
dot47 -->|letter gap<br>-1.3| letter109['EEE'<br>-56.4]
dot47 -->|word gap<br>-327.0| word109['EEE '<br>-382.1]
dash47 -->|symbol gap<br> -20.4| symbol110['EE-'<br>-126.9]
dash47 -->|letter gap<br>-1.3| letter110['EET'<br>-107.7]
dash47 -->|word gap<br>-327.0| word110['EET '<br>-433.5]
dot48 -->|symbol gap<br> -20.4| symbol111['M.'<br>-75.5]
dot48 -->|letter gap<br>-1.3| letter111['ME'<br>-56.3]
dot48 -->|word gap<br>-327.0| word111['ME '<br>-382.1]
dash48 -->|symbol gap<br> -20.4| symbol112['M-'<br>-126.8]
dash48 -->|letter gap<br>-1.3| letter112['MT'<br>-107.7]
dash48 -->|word gap<br>-327.0| word112['MT '<br>-433.4]
dot49 -->|symbol gap<br> -20.4| symbol113['E..'<br>-65.4]
dot49 -->|letter gap<br>-1.3| letter113['EI'<br>-46.3]
dot49 -->|word gap<br>-327.0| word113['EI '<br>-372.1]
dash49 -->|symbol gap<br> -20.4| symbol114['E.-'<br>-116.8]
dash49 -->|letter gap<br>-1.3| letter114['EA'<br>-97.7]
dash49 -->|word gap<br>-327.0| word114['EA '<br>-423.4]
dot50 -->|symbol gap<br> -20.4| symbol115['--.'<br>-65.4]
dot50 -->|letter gap<br>-1.3| letter115['G'<br>-46.2]
dot50 -->|word gap<br>-327.0| word115['G '<br>-372.0]
dash50 -->|symbol gap<br> -20.4| symbol116['---'<br>-116.8]
dash50 -->|letter gap<br>-1.3| letter116['O'<br>-97.6]
dash50 -->|word gap<br>-327.0| word116['O '<br>-423.4]
dot51 -->|symbol gap<br> -20.4| symbol117['I.'<br>-63.4]
dot51 -->|letter gap<br>-1.3| letter117['IE'<br>-44.2]
dot51 -->|word gap<br>-327.0| word117['IE '<br>-370.0]
dash51 -->|symbol gap<br> -20.4| symbol118['I-'<br>-114.7]
dash51 -->|letter gap<br>-1.3| letter118['IT'<br>-95.6]
dash51 -->|word gap<br>-327.0| word118['IT '<br>-421.4]
dot52 -->|symbol gap<br> -20.4| symbol119['...'<br>-53.3]
dot52 -->|letter gap<br>-1.3| letter119['S'<br>-34.1]
dot52 -->|word gap<br>-327.0| word119['S '<br>-359.9]
dash52 -->|symbol gap<br> -20.4| symbol120['..-'<br>-104.7]
dash52 -->|letter gap<br>-1.3| letter120['U'<br>-85.5]
dash52 -->|word gap<br>-327.0| word120['U '<br>-411.3]
dot53 -->|symbol gap<br> -20.4| symbol121['TE.'<br>-43.7]
dot53 -->|letter gap<br>-1.3| letter121['TEE'<br>-24.6]
dot53 -->|word gap<br>-327.0| word121['TEE '<br>-350.3]
dash53 -->|symbol gap<br> -20.4| symbol122['TE-'<br>-95.1]
dash53 -->|letter gap<br>-1.3| letter122['TET'<br>-75.9]
dash53 -->|word gap<br>-327.0| word122['TET '<br>-401.7]
dot54 -->|symbol gap<br> -20.4| symbol123['T..'<br>-33.6]
dot54 -->|letter gap<br>-1.3| letter123['TI'<br>-14.5]
dot54 -->|word gap<br>-327.0| word123['TI '<br>-340.3]
dash54 -->|symbol gap<br> -20.4| symbol124['T.-'<br>-85.0]
dash54 -->|letter gap<br>-1.3| letter124['TA'<br>-65.9]
dash54 -->|word gap<br>-327.0| word124['TA '<br>-391.6]
dot55 -->|symbol gap<br> -20.4| symbol125['N.'<br>-31.6]
dot55 -->|letter gap<br>-1.3| letter125['NE'<br>-12.4]
dot55 -->|word gap<br>-327.0| word125['NE '<br>-338.2]
dash55 -->|symbol gap<br> -20.4| symbol126['N-'<br>-82.9]
dash55 -->|letter gap<br>-1.3| letter126['NT'<br>-63.8]
dash55 -->|word gap<br>-327.0| word126['NT '<br>-389.6]
dot56 -->|symbol gap<br> -20.4| symbol127['-..'<br>-21.5]
dot56 -->|letter gap<br>-1.3| letter127['D'<br>-2.3]
dot56 -->|word gap<br>-327.0| word127['D '<br>-328.1]
dash56 -->|symbol gap<br> -20.4| symbol128['-.-'<br>-72.9]
dash56 -->|letter gap<br>-1.3| letter128['K'<br>-53.7]
dash56 -->|word gap<br>-327.0| word128['K '<br>-379.5]
