graph LR
start -->|dot<br>-31.9| dot0['.'<br>-31.9]
start -->|dash<br>-0.1| dash0['-'<br>-0.1]
dot0 -->|symbol gap<br> -0.0| symbol1['.'<br>-32.0]
dot0 -->|letter gap<br>-12.2| letter1['E'<br>-44.1]
dot0 -->|word gap<br>-520.8| word1['E '<br>-552.7]
dash0 -->|symbol gap<br> -0.0| symbol2['-'<br>-0.2]
dash0 -->|letter gap<br>-12.2| letter2['T'<br>-12.3]
dash0 -->|word gap<br>-520.8| word2['T '<br>-520.9]
letter2 -->|dot<br>-0.1| dot3['T.'<br>-12.4]
letter2 -->|dash<br>-44.0| dash3['T-'<br>-56.3]
symbol2 -->|dot<br>-0.1| dot4['.'<br>-0.3]
symbol2 -->|dash<br>-44.0| dash4['-'<br>-44.2]
dot3 -->|symbol gap<br> -0.1| symbol5['T.'<br>-12.6]
dot3 -->|letter gap<br>-10.2| letter5['TE'<br>-22.6]
dot3 -->|word gap<br>-494.1| word5['TE '<br>-506.5]
dash3 -->|symbol gap<br> -0.1| symbol6['T-'<br>-56.4]
dash3 -->|letter gap<br>-10.2| letter6['TT'<br>-66.5]
dash3 -->|word gap<br>-494.1| word6['TT '<br>-550.4]
dot4 -->|symbol gap<br> -0.1| symbol7['-.'<br>-0.4]
dot4 -->|letter gap<br>-10.2| letter7['N'<br>-10.5]
dot4 -->|word gap<br>-494.1| word7['N '<br>-494.4]
dash4 -->|symbol gap<br> -0.1| symbol8['--'<br>-44.3]
dash4 -->|letter gap<br>-10.2| letter8['M'<br>-54.4]
dash4 -->|word gap<br>-494.1| word8['M '<br>-538.2]
letter7 -->|dot<br>-0.7| dot9['N.'<br>-11.1]
letter7 -->|dash<br>-52.0| dash9['N-'<br>-62.5]
symbol7 -->|dot<br>-0.7| dot10['.'<br>-1.1]
symbol7 -->|dash<br>-52.0| dash10['-'<br>-52.4]
dot9 -->|symbol gap<br> -20.4| symbol11['N.'<br>-31.6]
dot9 -->|letter gap<br>-1.3| letter11['NE'<br>-12.4]
dot9 -->|word gap<br>-327.0| word11['NE '<br>-338.2]
dash9 -->|symbol gap<br> -20.4| symbol12['N-'<br>-82.9]
dash9 -->|letter gap<br>-1.3| letter12['NT'<br>-63.8]
dash9 -->|word gap<br>-327.0| word12['NT '<br>-389.6]
dot10 -->|symbol gap<br> -20.4| symbol13['-..'<br>-21.5]
dot10 -->|letter gap<br>-1.3| letter13['D'<br>-2.3]
dot10 -->|word gap<br>-327.0| word13['D '<br>-328.1]
dash10 -->|symbol gap<br> -20.4| symbol14['-.-'<br>-72.9]
dash10 -->|letter gap<br>-1.3| letter14['K'<br>-53.7]
dash10 -->|word gap<br>-327.0| word14['K '<br>-379.5]
letter11 -->|dot<br>-0.0| dot15['NE.'<br>-12.4]
letter11 -->|dash<br>-36.6| dash15['NE-'<br>-49.0]
letter13 -->|dot<br>-0.0| dot16['D.'<br>-2.4]
letter13 -->|dash<br>-36.6| dash16['D-'<br>-38.9]
dot15 -->|symbol gap<br> -0.0| symbol17['NE.'<br>-12.5]
dot15 -->|letter gap<br>-12.2| letter17['NEE'<br>-24.6]
dot15 -->|word gap<br>-520.8| word17['NEE '<br>-533.2]
dash15 -->|symbol gap<br> -0.0| symbol18['NE-'<br>-49.1]
dash15 -->|letter gap<br>-12.2| letter18['NET'<br>-61.2]
dash15 -->|word gap<br>-520.8| word18['NET '<br>-569.8]
dot16 -->|symbol gap<br> -0.0| symbol19['D.'<br>-2.4]
dot16 -->|letter gap<br>-12.2| letter19['DE'<br>-14.6]
dot16 -->|word gap<br>-520.8| word19['DE '<br>-523.1]
dash16 -->|symbol gap<br> -0.0| symbol20['D-'<br>-39.0]
dash16 -->|letter gap<br>-12.2| letter20['DT'<br>-51.1]
dash16 -->|word gap<br>-520.8| word20['DT '<br>-559.7]
symbol17 -->|dot<br>-26.5| dot21['NE.'<br>-39.0]
symbol17 -->|dash<br>-0.1| dash21['NE-'<br>-12.5]
symbol19 -->|dot<br>-26.5| dot22['D.'<br>-29.0]
symbol19 -->|dash<br>-0.1| dash22['D-'<br>-2.5]
dot21 -->|symbol gap<br> -0.0| symbol23['NE..'<br>-39.1]
dot21 -->|letter gap<br>-12.2| letter23['NEI'<br>-51.2]
dot21 -->|word gap<br>-520.8| word23['NEI '<br>-559.8]
dash21 -->|symbol gap<br> -0.0| symbol24['NE.-'<br>-12.6]
dash21 -->|letter gap<br>-12.2| letter24['NEA'<br>-24.7]
dash21 -->|word gap<br>-520.8| word24['NEA '<br>-533.3]
dot22 -->|symbol gap<br> -0.0| symbol25['D..'<br>-29.0]
dot22 -->|letter gap<br>-12.2| letter25['DI'<br>-41.2]
dot22 -->|word gap<br>-520.8| word25['DI '<br>-549.7]
dash22 -->|symbol gap<br> -0.0| symbol26['D.-'<br>-2.5]
dash22 -->|letter gap<br>-12.2| letter26['DA'<br>-14.7]
dash22 -->|word gap<br>-520.8| word26['DA '<br>-523.2]
symbol24 -->|dot<br>-0.0| dot27['NE.'<br>-12.6]
symbol24 -->|dash<br>-36.6| dash27['NE-'<br>-49.2]
symbol26 -->|dot<br>-0.0| dot28['D.'<br>-2.5]
symbol26 -->|dash<br>-36.6| dash28['D-'<br>-39.1]
dot27 -->|symbol gap<br> -0.0| symbol29['NE.-.'<br>-12.7]
dot27 -->|letter gap<br>-12.2| letter29['NER'<br>-24.8]
dot27 -->|word gap<br>-520.8| word29['NER '<br>-533.4]
dash27 -->|symbol gap<br> -0.0| symbol30['NE.--'<br>-49.2]
dash27 -->|letter gap<br>-12.2| letter30['NEW'<br>-61.4]
dash27 -->|word gap<br>-520.8| word30['NEW '<br>-570.0]
dot28 -->|symbol gap<br> -0.0| symbol31['D.-.'<br>-2.6]
dot28 -->|letter gap<br>-12.2| letter31['DR'<br>-14.7]
dot28 -->|word gap<br>-520.8| word31['DR '<br>-523.3]
dash28 -->|symbol gap<br> -0.0| symbol32['D.--'<br>-39.2]
dash28 -->|letter gap<br>-12.2| letter32['DW'<br>-51.3]
dash28 -->|word gap<br>-520.8| word32['DW '<br>-559.9]
symbol29 -->|dot<br>-0.1| dot33['NE.'<br>-12.8]
symbol29 -->|dash<br>-44.0| dash33['NE-'<br>-56.7]
symbol31 -->|dot<br>-0.1| dot34['D.'<br>-2.7]
symbol31 -->|dash<br>-44.0| dash34['D-'<br>-46.6]
dot33 -->|symbol gap<br> -39.6| symbol35['NE.-..'<br>-52.4]
dot33 -->|letter gap<br>-0.1| letter35['NEL'<br>-12.8]
dot33 -->|word gap<br>-266.0| word35['NEL '<br>-278.7]
dash33 -->|symbol gap<br> -39.6| symbol36['NE.-.-'<br>-96.3]
dot34 -->|symbol gap<br> -39.6| symbol37['D.-..'<br>-42.3]
dot34 -->|letter gap<br>-0.1| letter37['DL'<br>-2.7]
dot34 -->|word gap<br>-266.0| word37['DL '<br>-268.7]
dash34 -->|symbol gap<br> -39.6| symbol38['D.-.-'<br>-86.2]
letter35 -->|dot<br>-31.9| dot39['NEL.'<br>-44.7]
letter35 -->|dash<br>-0.1| dash39['NEL-'<br>-12.9]
letter37 -->|dot<br>-31.9| dot40['DL.'<br>-34.7]
letter37 -->|dash<br>-0.1| dash40['DL-'<br>-2.9]
dot39 -->|symbol gap<br> -0.0| symbol41['NEL.'<br>-44.8]
dot39 -->|letter gap<br>-12.2| letter41['NELE'<br>-56.9]
dot39 -->|word gap<br>-520.8| word41['NELE '<br>-565.5]
dash39 -->|symbol gap<br> -0.0| symbol42['NEL-'<br>-13.0]
dash39 -->|letter gap<br>-12.2| letter42['NELT'<br>-25.1]
dash39 -->|word gap<br>-520.8| word42['NELT '<br>-533.7]
dot40 -->|symbol gap<br> -0.0| symbol43['DL.'<br>-34.7]
dot40 -->|letter gap<br>-12.2| letter43['DLE'<br>-46.9]
dot40 -->|word gap<br>-520.8| word43['DLE '<br>-555.4]
dash40 -->|symbol gap<br> -0.0| symbol44['DL-'<br>-2.9]
dash40 -->|letter gap<br>-12.2| letter44['DLT'<br>-15.1]
dash40 -->|word gap<br>-520.8| word44['DLT '<br>-523.6]
symbol42 -->|dot<br>-31.9| dot45['NEL.'<br>-44.9]
symbol42 -->|dash<br>-0.1| dash45['NEL-'<br>-13.1]
symbol44 -->|dot<br>-31.9| dot46['DL.'<br>-34.8]
symbol44 -->|dash<br>-0.1| dash46['DL-'<br>-3.0]
dot45 -->|symbol gap<br> -0.0| symbol47['NEL-.'<br>-45.0]
dot45 -->|letter gap<br>-12.2| letter47['NELN'<br>-57.1]
dot45 -->|word gap<br>-520.8| word47['NELN '<br>-565.7]
dash45 -->|symbol gap<br> -0.0| symbol48['NEL--'<br>-13.2]
dash45 -->|letter gap<br>-12.2| letter48['NELM'<br>-25.3]
dash45 -->|word gap<br>-520.8| word48['NELM '<br>-533.9]
dot46 -->|symbol gap<br> -0.0| symbol49['DL-.'<br>-34.9]
dot46 -->|letter gap<br>-12.2| letter49['DLN'<br>-47.0]
dot46 -->|word gap<br>-520.8| word49['DLN '<br>-555.6]
dash46 -->|symbol gap<br> -0.0| symbol50['DL--'<br>-3.1]
dash46 -->|letter gap<br>-12.2| letter50['DLM'<br>-15.2]
dash46 -->|word gap<br>-520.8| word50['DLM '<br>-523.8]
symbol48 -->|dot<br>-26.5| dot51['NEL.'<br>-39.7]
symbol48 -->|dash<br>-0.1| dash51['NEL-'<br>-13.2]
symbol50 -->|dot<br>-26.5| dot52['DL.'<br>-29.6]
symbol50 -->|dash<br>-0.1| dash52['DL-'<br>-3.1]
dot51 -->|symbol gap<br> -0.0| symbol53['NEL--.'<br>-39.7]
dot51 -->|letter gap<br>-12.2| letter53['NELG'<br>-51.9]
dot51 -->|word gap<br>-520.8| word53['NELG '<br>-560.5]
dash51 -->|symbol gap<br> -0.0| symbol54['NEL---'<br>-13.3]
dash51 -->|letter gap<br>-12.2| letter54['NELO'<br>-25.4]
dash51 -->|word gap<br>-520.8| word54['NELO '<br>-534.0]
dot52 -->|symbol gap<br> -0.0| symbol55['DL--.'<br>-29.7]
dot52 -->|letter gap<br>-12.2| letter55['DLG'<br>-41.8]
dot52 -->|word gap<br>-520.8| word55['DLG '<br>-550.4]
dash52 -->|symbol gap<br> -0.0| symbol56['DL---'<br>-3.2]
dash52 -->|letter gap<br>-12.2| letter56['DLO'<br>-15.3]
dash52 -->|word gap<br>-520.8| word56['DLO '<br>-523.9]
symbol54 -->|dot<br>-31.9| dot57['NEL.'<br>-45.2]
symbol54 -->|dash<br>-0.1| dash57['NEL-'<br>-13.4]
symbol56 -->|dot<br>-31.9| dot58['DL.'<br>-35.1]
symbol56 -->|dash<br>-0.1| dash58['DL-'<br>-3.3]
dot57 -->|symbol gap<br> -0.0| symbol59['NEL---.'<br>-45.2]
dash57 -->|symbol gap<br> -0.0| symbol60['NEL----'<br>-13.4]
dot58 -->|symbol gap<br> -0.0| symbol61['DL---.'<br>-35.1]
dash58 -->|symbol gap<br> -0.0| symbol62['DL----'<br>-3.3]
symbol60 -->|dot<br>-0.1| dot63['NEL.'<br>-13.5]
symbol60 -->|dash<br>-44.0| dash63['NEL-'<br>-57.4]
symbol62 -->|dot<br>-0.1| dot64['DL.'<br>-3.4]
symbol62 -->|dash<br>-44.0| dash64['DL-'<br>-47.3]
dot63 -->|symbol gap<br> -8819.1| symbol65['NEL----.'<br>-8832.6]
dot63 -->|letter gap<br>-1898.4| letter65['NEL9'<br>-1911.9]
dot63 -->|word gap<br>0.0| word65['NEL9 '<br>-13.5]
dash63 -->|symbol gap<br> -8819.1| symbol66['NEL-----'<br>-8876.5]
dash63 -->|letter gap<br>-1898.4| letter66['NEL0'<br>-1955.8]
dash63 -->|word gap<br>0.0| word66['NEL0 '<br>-57.4]
dot64 -->|symbol gap<br> -8819.1| symbol67['DL----.'<br>-8822.6]
dot64 -->|letter gap<br>-1898.4| letter67['DL9'<br>-1901.9]
dot64 -->|word gap<br>0.0| word67['DL9 '<br>-3.4]
dash64 -->|symbol gap<br> -8819.1| symbol68['DL-----'<br>-8866.5]
dash64 -->|letter gap<br>-1898.4| letter68['DL0'<br>-1945.7]
dash64 -->|word gap<br>0.0| word68['DL0 '<br>-47.3]
word65 -->|dot<br>-26.5| dot69['NEL9 .'<br>-40.1]
word65 -->|dash<br>-0.1| dash69['NEL9 -'<br>-13.6]
word67 -->|dot<br>-26.5| dot70['DL9 .'<br>-30.0]
word67 -->|dash<br>-0.1| dash70['DL9 -'<br>-3.5]
dot69 -->|symbol gap<br> -0.7| symbol71['NEL9 .'<br>-40.7]
dot69 -->|letter gap<br>-14.3| letter71['NEL9 E'<br>-54.4]
dot69 -->|word gap<br>-548.1| word71['NEL9 E '<br>-588.2]
dash69 -->|symbol gap<br> -0.7| symbol72['NEL9 -'<br>-14.2]
dash69 -->|letter gap<br>-14.3| letter72['NEL9 T'<br>-27.9]
dash69 -->|word gap<br>-548.1| word72['NEL9 T '<br>-561.7]
dot70 -->|symbol gap<br> -0.7| symbol73['DL9 .'<br>-30.6]
dot70 -->|letter gap<br>-14.3| letter73['DL9 E'<br>-44.3]
dot70 -->|word gap<br>-548.1| word73['DL9 E '<br>-578.1]
dash70 -->|symbol gap<br> -0.7| symbol74['DL9 -'<br>-4.2]
dash70 -->|letter gap<br>-14.3| letter74['DL9 T'<br>-17.9]
dash70 -->|word gap<br>-548.1| word74['DL9 T '<br>-551.6]
symbol72 -->|dot<br>-0.0| dot75['NEL9 .'<br>-14.3]
symbol72 -->|dash<br>-36.6| dash75['NEL9 -'<br>-50.8]
symbol74 -->|dot<br>-0.0| dot76['DL9 .'<br>-4.2]
symbol74 -->|dash<br>-36.6| dash76['DL9 -'<br>-40.8]
dot75 -->|symbol gap<br> -0.0| symbol77['NEL9 -.'<br>-14.3]
dot75 -->|letter gap<br>-12.2| letter77['NEL9 N'<br>-26.5]
dot75 -->|word gap<br>-520.8| word77['NEL9 N '<br>-535.0]
dash75 -->|symbol gap<br> -0.0| symbol78['NEL9 --'<br>-50.9]
dash75 -->|letter gap<br>-12.2| letter78['NEL9 M'<br>-63.0]
dash75 -->|word gap<br>-520.8| word78['NEL9 M '<br>-571.6]
dot76 -->|symbol gap<br> -0.0| symbol79['DL9 -.'<br>-4.2]
dot76 -->|letter gap<br>-12.2| letter79['DL9 N'<br>-16.4]
dot76 -->|word gap<br>-520.8| word79['DL9 N '<br>-525.0]
dash76 -->|symbol gap<br> -0.0| symbol80['DL9 --'<br>-40.8]
dash76 -->|letter gap<br>-12.2| letter80['DL9 M'<br>-53.0]
dash76 -->|word gap<br>-520.8| word80['DL9 M '<br>-561.5]
symbol77 -->|dot<br>-26.5| dot81['NEL9 .'<br>-40.9]
symbol77 -->|dash<br>-0.1| dash81['NEL9 -'<br>-14.4]
symbol79 -->|dot<br>-26.5| dot82['DL9 .'<br>-30.8]
symbol79 -->|dash<br>-0.1| dash82['DL9 -'<br>-4.3]
dot81 -->|symbol gap<br> -0.0| symbol83['NEL9 -..'<br>-40.9]
dot81 -->|letter gap<br>-12.2| letter83['NEL9 D'<br>-53.1]
dot81 -->|word gap<br>-520.8| word83['NEL9 D '<br>-561.6]
dash81 -->|symbol gap<br> -0.0| symbol84['NEL9 -.-'<br>-14.4]
dash81 -->|letter gap<br>-12.2| letter84['NEL9 K'<br>-26.6]
dash81 -->|word gap<br>-520.8| word84['NEL9 K '<br>-535.1]
dot82 -->|symbol gap<br> -0.0| symbol85['DL9 -..'<br>-30.8]
dot82 -->|letter gap<br>-12.2| letter85['DL9 D'<br>-43.0]
dot82 -->|word gap<br>-520.8| word85['DL9 D '<br>-551.5]
dash82 -->|symbol gap<br> -0.0| symbol86['DL9 -.-'<br>-4.3]
dash82 -->|letter gap<br>-12.2| letter86['DL9 K'<br>-16.5]
dash82 -->|word gap<br>-520.8| word86['DL9 K '<br>-525.1]
symbol84 -->|dot<br>-0.0| dot87['NEL9 .'<br>-14.4]
symbol84 -->|dash<br>-36.6| dash87['NEL9 -'<br>-51.0]
symbol86 -->|dot<br>-0.0| dot88['DL9 .'<br>-4.4]
symbol86 -->|dash<br>-36.6| dash88['DL9 -'<br>-40.9]
dot87 -->|symbol gap<br> -47.4| symbol89['NEL9 -.-.'<br>-61.9]
dot87 -->|letter gap<br>-0.0| letter89['NEL9 C'<br>-14.4]
dot87 -->|word gap<br>-247.0| word89['NEL9 C '<br>-261.4]
dash87 -->|symbol gap<br> -47.4| symbol90['NEL9 -.--'<br>-98.5]
dash87 -->|letter gap<br>-0.0| letter90['NEL9 Y'<br>-51.0]
dash87 -->|word gap<br>-247.0| word90['NEL9 Y '<br>-298.0]
dot88 -->|symbol gap<br> -47.4| symbol91['DL9 -.-.'<br>-51.8]
dot88 -->|letter gap<br>-0.0| letter91['DL9 C'<br>-4.4]
dot88 -->|word gap<br>-247.0| word91['DL9 C '<br>-251.4]
dash88 -->|symbol gap<br> -47.4| symbol92['DL9 -.--'<br>-88.4]
dash88 -->|letter gap<br>-0.0| letter92['DL9 Y'<br>-41.0]
dash88 -->|word gap<br>-247.0| word92['DL9 Y '<br>-288.0]
letter89 -->|dot<br>-31.9| dot93['NEL9 C.'<br>-46.4]
letter89 -->|dash<br>-0.1| dash93['NEL9 C-'<br>-14.6]
letter91 -->|dot<br>-31.9| dot94['DL9 C.'<br>-36.3]
letter91 -->|dash<br>-0.1| dash94['DL9 C-'<br>-4.5]
dot93 -->|symbol gap<br> -0.0| symbol95['NEL9 C.'<br>-46.4]
dot93 -->|letter gap<br>-12.2| letter95['NEL9 CE'<br>-58.6]
dot93 -->|word gap<br>-520.8| word95['NEL9 CE '<br>-567.1]
dash93 -->|symbol gap<br> -0.0| symbol96['NEL9 C-'<br>-14.6]
dash93 -->|letter gap<br>-12.2| letter96['NEL9 CT'<br>-26.8]
dash93 -->|word gap<br>-520.8| word96['NEL9 CT '<br>-535.3]
dot94 -->|symbol gap<br> -0.0| symbol97['DL9 C.'<br>-36.3]
dot94 -->|letter gap<br>-12.2| letter97['DL9 CE'<br>-48.5]
dot94 -->|word gap<br>-520.8| word97['DL9 CE '<br>-557.1]
dash94 -->|symbol gap<br> -0.0| symbol98['DL9 C-'<br>-4.5]
dash94 -->|letter gap<br>-12.2| letter98['DL9 CT'<br>-16.7]
dash94 -->|word gap<br>-520.8| word98['DL9 CT '<br>-525.3]
symbol96 -->|dot<br>-26.5| dot99['NEL9 C.'<br>-41.2]
symbol96 -->|dash<br>-0.1| dash99['NEL9 C-'<br>-14.7]
symbol98 -->|dot<br>-26.5| dot100['DL9 C.'<br>-31.1]
symbol98 -->|dash<br>-0.1| dash100['DL9 C-'<br>-4.6]
dot99 -->|symbol gap<br> -0.0| symbol101['NEL9 C-.'<br>-41.2]
dot99 -->|letter gap<br>-12.2| letter101['NEL9 CN'<br>-53.4]
dot99 -->|word gap<br>-520.8| word101['NEL9 CN '<br>-561.9]
dash99 -->|symbol gap<br> -0.0| symbol102['NEL9 C--'<br>-14.7]
dash99 -->|letter gap<br>-12.2| letter102['NEL9 CM'<br>-26.9]
dash99 -->|word gap<br>-520.8| word102['NEL9 CM '<br>-535.4]
dot100 -->|symbol gap<br> -0.0| symbol103['DL9 C-.'<br>-31.1]
dot100 -->|letter gap<br>-12.2| letter103['DL9 CN'<br>-43.3]
dot100 -->|word gap<br>-520.8| word103['DL9 CN '<br>-551.9]
dash100 -->|symbol gap<br> -0.0| symbol104['DL9 C--'<br>-4.6]
dash100 -->|letter gap<br>-12.2| letter104['DL9 CM'<br>-16.8]
dash100 -->|word gap<br>-520.8| word104['DL9 CM '<br>-525.4]
symbol102 -->|dot<br>-0.0| dot105['NEL9 C.'<br>-14.7]
symbol102 -->|dash<br>-36.6| dash105['NEL9 C-'<br>-51.3]
symbol104 -->|dot<br>-0.0| dot106['DL9 C.'<br>-4.7]
symbol104 -->|dash<br>-36.6| dash106['DL9 C-'<br>-41.3]
dot105 -->|symbol gap<br> -0.0| symbol107['NEL9 C--.'<br>-14.8]
dot105 -->|letter gap<br>-12.2| letter107['NEL9 CG'<br>-26.9]
dot105 -->|word gap<br>-520.8| word107['NEL9 CG '<br>-535.5]
dash105 -->|symbol gap<br> -0.0| symbol108['NEL9 C---'<br>-51.4]
dash105 -->|letter gap<br>-12.2| letter108['NEL9 CO'<br>-63.5]
dash105 -->|word gap<br>-520.8| word108['NEL9 CO '<br>-572.1]
dot106 -->|symbol gap<br> -0.0| symbol109['DL9 C--.'<br>-4.7]
dot106 -->|letter gap<br>-12.2| letter109['DL9 CG'<br>-16.9]
dot106 -->|word gap<br>-520.8| word109['DL9 CG '<br>-525.4]
dash106 -->|symbol gap<br> -0.0| symbol110['DL9 C---'<br>-41.3]
dash106 -->|letter gap<br>-12.2| letter110['DL9 CO'<br>-53.4]
dash106 -->|word gap<br>-520.8| word110['DL9 CO '<br>-562.0]
symbol107 -->|dot<br>-26.5| dot111['NEL9 C.'<br>-41.3]
symbol107 -->|dash<br>-0.1| dash111['NEL9 C-'<br>-14.8]
symbol109 -->|dot<br>-26.5| dot112['DL9 C.'<br>-31.3]
symbol109 -->|dash<br>-0.1| dash112['DL9 C-'<br>-4.8]
dot111 -->|symbol gap<br> -3072.6| symbol113['NEL9 C--..'<br>-3114.0]
dot111 -->|letter gap<br>-592.0| letter113['NEL9 CZ'<br>-633.4]
dot111 -->|word gap<br>0.0| word113['NEL9 CZ '<br>-41.3]
dash111 -->|symbol gap<br> -3072.6| symbol114['NEL9 C--.-'<br>-3087.5]
dash111 -->|letter gap<br>-592.0| letter114['NEL9 CQ'<br>-606.9]
dash111 -->|word gap<br>0.0| word114['NEL9 CQ '<br>-14.8]
dot112 -->|symbol gap<br> -3072.6| symbol115['DL9 C--..'<br>-3103.9]
dot112 -->|letter gap<br>-592.0| letter115['DL9 CZ'<br>-623.3]
dot112 -->|word gap<br>0.0| word115['DL9 CZ '<br>-31.3]
dash112 -->|symbol gap<br> -3072.6| symbol116['DL9 C--.-'<br>-3077.4]
dash112 -->|letter gap<br>-592.0| letter116['DL9 CQ'<br>-596.8]
dash112 -->|word gap<br>0.0| word116['DL9 CQ '<br>-4.8]
